import { InterDeptTicket } from "@/types";

export const mockTickets: InterDeptTicket[] = [
  { id: "TKT-1001", subject: "Laptop screen flickering", description: "The screen of my Dell laptop keeps flickering when plugged into the docking station. Need urgent help as it hurts my eyes.", raisedByDept: "Marketing", raisedByHodName: "Priya Singh", raisedByHodEmail: "priya.singh@dritgroup.com", raisedByHodPhone: "+91 98765 11111", assignedToDept: "Information Technology", handler: "Ravi Rai", status: "In Progress", priority: "High", dateRaised: "2024-03-10" },
  { id: "TKT-1002", subject: "New employee onboarding access", description: "Please create email and ERP portal access for the 3 new executives joining next week.", raisedByDept: "Human Resources", raisedByHodName: "Sita Sharma", raisedByHodEmail: "sita.sharma@dritgroup.com", raisedByHodPhone: "+91 98765 22222", assignedToDept: "Information Technology", handler: null, status: "Pending", priority: "Medium", dateRaised: "2024-03-12" },
  { id: "TKT-1003", subject: "Budget approval for Q2 campaign", description: "We need the finance team to approve the $50k budget for the upcoming Q2 digital marketing campaigns.", raisedByDept: "Marketing", raisedByHodName: "Priya Singh", raisedByHodEmail: "priya.singh@dritgroup.com", raisedByHodPhone: "+91 98765 11111", assignedToDept: "Finance", handler: "Amit Kumar", status: "Completed", priority: "High", dateRaised: "2024-02-28" },
  { id: "TKT-1004", subject: "Air conditioning not working", description: "The AC unit in the Server room is making weird noises and blowing warm air. Please fix immediately.", raisedByDept: "Information Technology", raisedByHodName: "Ravi Rai", raisedByHodEmail: "ravi.rai@dritgroup.com", raisedByHodPhone: "+91 98765 33333", assignedToDept: "Operations", handler: "Rahul Verma", status: "In Progress", priority: "Medium", dateRaised: "2024-03-11" },
  { id: "TKT-1005", subject: "Payroll query for Jan 2024", description: "Several support agents have reported anomalies in their January performance bonus calculation.", raisedByDept: "Customer Support", raisedByHodName: "Neha Gupta", raisedByHodEmail: "neha.gupta@dritgroup.com", raisedByHodPhone: "+91 98765 44444", assignedToDept: "Finance", handler: null, status: "Pending", priority: "Low", dateRaised: "2024-03-14" },
  { id: "TKT-1006", subject: "Need dual monitors setup", description: "Our R&D researchers need dual monitors to trace the new architecture properly.", raisedByDept: "Research & Development", raisedByHodName: "Vikas Joshi", raisedByHodEmail: "vikas.joshi@dritgroup.com", raisedByHodPhone: "+91 98765 55555", assignedToDept: "Information Technology", handler: "Sita Sharma", status: "Completed", priority: "Low", dateRaised: "2024-01-20" },
  { id: "TKT-1007", subject: "Customer data export request", description: "Requesting a full SQL dump of the old customer leads for the 2023 operations audit.", raisedByDept: "Operations", raisedByHodName: "Rahul Verma", raisedByHodEmail: "rahul.verma@dritgroup.com", raisedByHodPhone: "+91 98765 66666", assignedToDept: "Customer Support", handler: "Neha Gupta", status: "Pending", priority: "High", dateRaised: "2024-03-15" },
];
